#!/bin/bash -e
if [[ ! -f "/home/spark-cb0e7192-6a8a-4ca6-8760-97/tmp/uv/uv_0.6.10_linux_arm64" ]]; then
  curl -LsSf https://astral.sh/uv/0.6.10/install.sh | sh
  exec "$HOME/.local/bin/uv" "$@"
fi
exec "/home/spark-cb0e7192-6a8a-4ca6-8760-97/tmp/uv/uv_0.6.10_linux_arm64" "$@"
